<?php

const CONNECT_MATOMO_VERSION = '1.0.30';
const CONNECT_MATOMO_REVISION = 2023092201;

if (!defined('NAMESPACE_SEPARATOR')) {
    define("NAMESPACE_SEPARATOR", '\\');
}

const CONNECT_MATOMO_PATH = dirname(__FILE__) . DIRECTORY_SEPARATOR;
